// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/greet/greet.proto

package greet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GreetStreamRequest) Reset() {
	*x = GreetStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_greet_greet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetStreamRequest) ProtoMessage() {}

func (x *GreetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_greet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetStreamRequest.ProtoReflect.Descriptor instead.
func (*GreetStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_greet_greet_proto_rawDescGZIP(), []int{0}
}

func (x *GreetStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *GreetStreamResponse) Reset() {
	*x = GreetStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_greet_greet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetStreamResponse) ProtoMessage() {}

func (x *GreetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_greet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetStreamResponse.ProtoReflect.Descriptor instead.
func (*GreetStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_greet_greet_proto_rawDescGZIP(), []int{1}
}

func (x *GreetStreamResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type GreetServerStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GreetServerStreamRequest) Reset() {
	*x = GreetServerStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_greet_greet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetServerStreamRequest) ProtoMessage() {}

func (x *GreetServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_greet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetServerStreamRequest.ProtoReflect.Descriptor instead.
func (*GreetServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_greet_greet_proto_rawDescGZIP(), []int{2}
}

func (x *GreetServerStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetServerStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *GreetServerStreamResponse) Reset() {
	*x = GreetServerStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_greet_greet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetServerStreamResponse) ProtoMessage() {}

func (x *GreetServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_greet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetServerStreamResponse.ProtoReflect.Descriptor instead.
func (*GreetServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_greet_greet_proto_rawDescGZIP(), []int{3}
}

func (x *GreetServerStreamResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_proto_greet_greet_proto protoreflect.FileDescriptor

var file_proto_greet_greet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x22, 0x28, 0x0a, 0x12, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x2e, 0x0a,
	0x18, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a,
	0x19, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x32, 0xb6, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x3b, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_greet_greet_proto_rawDescOnce sync.Once
	file_proto_greet_greet_proto_rawDescData = file_proto_greet_greet_proto_rawDesc
)

func file_proto_greet_greet_proto_rawDescGZIP() []byte {
	file_proto_greet_greet_proto_rawDescOnce.Do(func() {
		file_proto_greet_greet_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_greet_greet_proto_rawDescData)
	})
	return file_proto_greet_greet_proto_rawDescData
}

var file_proto_greet_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_greet_greet_proto_goTypes = []any{
	(*GreetStreamRequest)(nil),        // 0: greet.GreetStreamRequest
	(*GreetStreamResponse)(nil),       // 1: greet.GreetStreamResponse
	(*GreetServerStreamRequest)(nil),  // 2: greet.GreetServerStreamRequest
	(*GreetServerStreamResponse)(nil), // 3: greet.GreetServerStreamResponse
}
var file_proto_greet_greet_proto_depIdxs = []int32{
	0, // 0: greet.GreetService.GreetStream:input_type -> greet.GreetStreamRequest
	2, // 1: greet.GreetService.GreetServerStream:input_type -> greet.GreetServerStreamRequest
	1, // 2: greet.GreetService.GreetStream:output_type -> greet.GreetStreamResponse
	3, // 3: greet.GreetService.GreetServerStream:output_type -> greet.GreetServerStreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greet_greet_proto_init() }
func file_proto_greet_greet_proto_init() {
	if File_proto_greet_greet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_greet_greet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GreetStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_greet_greet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GreetStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_greet_greet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GreetServerStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_greet_greet_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GreetServerStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_greet_greet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greet_greet_proto_goTypes,
		DependencyIndexes: file_proto_greet_greet_proto_depIdxs,
		MessageInfos:      file_proto_greet_greet_proto_msgTypes,
	}.Build()
	File_proto_greet_greet_proto = out.File
	file_proto_greet_greet_proto_rawDesc = nil
	file_proto_greet_greet_proto_goTypes = nil
	file_proto_greet_greet_proto_depIdxs = nil
}
